### ISSUE TITLE
Play song

### ISSUE THREAD

**Issue by Hecktors** [Hecktors/rueda-de-casino#1]
## Value statement
As a **user**
I need **a play, pause and stop button**
so that **I can control the music play status**

## Description
![image](https://user-images.githubusercontent.com/24996874/99251421-9b4af980-280d-11eb-9286-3dfefee0908d.png)

## Acceptance criteria
- [x] In default-state the main button has a play icon
- [x] In default-state clicking the main button causes the play-state
- [x] In play-state an audio song plays
- [x] In play-state the main button has a pause icon
- [x] In play-state clicking the main button causes pause-state
- [x] In pause-state the audio pauses
- [x] In pause-state the main button has a play icon
- [x] In pause-state clicking the main button causes the play-state
- [x] In pause-state appears a stop button
- [x] Clicking the stop button causes the stop of the audio
- [x] Clicking the stop button causes the default-state

## Tasks
- [x] Add main button
- [x] Add stop button
- [x] Create isRunning and isPaused hooks 
- [x] Show icon on main button depending on states
- [x] Show stop button depending on states
- [x] Import audio song
- [x] Play, pause and stop song, depending on state
- [x] Testing

## Size
medium
