### ISSUE TITLE
Move call speed select

### ISSUE THREAD

**Issue by Hecktors** [Hecktors/rueda-de-casino#10]
## Value statement
As a **user** 
I need **I can select no song and choose the speed of the move calls** 
so that **I can use the app inpendently of the app provided songs** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/24996874/99917134-a66ebf80-2d0e-11eb-8be5-053f4781e156.png)

## Acceptance criteria
- [x] A additional radio button have the option of no song
- [x] 5 diffents speed options are selectable by a range input

## Tasks
- [x] Add a radio
- [x] Show the range input after choosing that radio
- [x] Adapt choosen speed to move audio call speed logic
- [x] Test: Display radio, range input

## Size
medium
