### ISSUE TITLE
List move names

### ISSUE THREAD

**Issue by Hecktors** [Hecktors/rueda-de-casino#2]
## Value statement
As a **user**
I need **I can see the move names to pratice**
so that **I have an overview of what to expect**

## Description
![image](https://user-images.githubusercontent.com/24996874/99730935-69f85500-2abd-11eb-9065-a16dee93de35.png)

## Acceptance criteria
- [x] The move titles are listed during the default and pause state.
- [x] In play state every 10 sec a random move title is displayed

## Tasks
- [x] Create json file including move objects: id, name
- [x] Create moveList component
- [x] Show moveList
- [x] Hide moveList in play mode 
- [x] Build interval and random logic for move change
- [x] Show current move in play mode
- [x] Testing

## Size
medium
