### ISSUE TITLE
Add backend using expess server

### ISSUE THREAD

**Issue by Hecktors** [Hecktors/rueda-de-casino#21]
## Acceptance criteria
- [x] Build backend
- [x] Add express server
- [x] Add mongoDB 

## Tasks
- [x] Setup backend
- [x] Install express, mongoose
- [x] Create express server
- [x] Create collection using Atlas service
- [x] Connet mongoose to Altas

## Complexity
medium
