### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by Hecktors** [Hecktors/rueda-de-casino#24]
## Value statement
As a **user** 
I need ** I can use the app on mobil in portrait and landscape view and on desktop** 
so that **I have a nice user experience** 

## Acceptance criteria
- [x] Optimize the app for mobil portrait and landscape view
- [x] Also accessible for desktop view

## Tasks
- [x] Optimize stylesheets for landscape view
- [x] Desktop view in landscape view, max-width 800px 

## Complexity
medium
