### ISSUE TITLE
Backend request: get audios

### ISSUE THREAD

**Issue by Hecktors** [Hecktors/rueda-de-casino#25]
## Acceptance criteria
- [ ] Get-request ('/audios') responses with all audios

## Tasks
- [ ] Install multer
- [ ] Add ('/audios') router
- [ ] Response with audio files array if success, with error message if failed

## Complexity
low
