### ISSUE TITLE
Move call animation

### ISSUE THREAD

**Issue by Hecktors** [Hecktors/rueda-de-casino#26]
## Acceptance criteria
- [x] Animate move calls: grow in and fade out

## Tasks
- [x] Install react-transition-gruop
- [x] Build animation of current move

## Complexity
low
