### ISSUE TITLE
Play move audio

### ISSUE THREAD

**Issue by Hecktors** [Hecktors/rueda-de-casino#3]
## Value statement
As a **user**
I need **to hear the random move name after a specific amount of time**
so that **I know which move to dance**

## Description
![image](https://user-images.githubusercontent.com/24996874/99273751-bc214800-2829-11eb-9ce3-4f13a24d88b3.png)

## Acceptance criteria
- [x] The audio plays with the apperance of the current move name
- [x] The proximate move name is seen an heard after a break depending on its individual amount of steps

## Tasks
- [x] Add audio file for each move
- [x] Add path links to data.json
- [x] Build handle audio logic 

## Size
small
