### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Hecktors** [Hecktors/rueda-de-casino#38]
## Acceptance criteria
- [ ] Write the Read.me file

## Tasks
- [ ] Add description
- [ ] Add header image and mockup image
- [ ] Add features
- [ ] Add Tech stack

## Complexity
low
