### ISSUE TITLE
Youtube video

### ISSUE THREAD

**Issue by Hecktors** [Hecktors/rueda-de-casino#4]
## Value statement
As a **user**
I need **can see a video to each move**
so that **I see and remember how to perform that move**

## Description
![image](https://user-images.githubusercontent.com/24996874/99909737-8fb67180-2cea-11eb-8f24-272e2a0981fb.png)

## Acceptance criteria
- [x] Click on a move from the move list causes a video overlay
- [x] Click on the cancel button closes the video

## Tasks
- [x] Create a video overlay component
- [x] Add youtube url to each move object
- [x] Add video start-time to each move object
- [x] Make move list items clickable

## Size
medium
