### ISSUE TITLE
User authentification

### ISSUE THREAD

**Issue by Hecktors** [Hecktors/rueda-de-casino#40]
## Value statement
As a **user** 
I need **I can create and use an account** 
so that ** I can manage my induvidual moves** 

## Acceptance criteria
- [ ] Build a login page
- [ ] The user can create an account
- [ ] The user can sing up, log in, log out, and delete the accout

## Tasks
- [ ] Login page
- [ ] User database
- [ ] Encrypt password saving in database
- [ ] Email notification
- [ ] Relationship between user and level / moves data

## Complexity
high
