### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by Hecktors** [Hecktors/rueda-de-casino#41]
## Value statement
As a **user** 
I need **to have a pwa** 
so that **my moves are stored on my device** 

## Acceptance criteria
- [ ] Convert app to pwa

## Tasks
- [ ] Add service worker
- [ ] Add favicons for div platforms

## Complexity
medium
