### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by Hecktors** [Hecktors/rueda-de-casino#44]
## Value statement
As a **user** 
I need **navigation bar** 
so that **I have a better user experience** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/24996874/103691337-4c604b80-4f96-11eb-8426-4aed2065c412.png)

## Acceptance criteria
- [x] The navigation bar is always displayed, except in authentication, session, YouTube video mode
- [x] Homepage: music playlist icon
- [x] Settings: settings icon
- [x] Edit: Pencil Icon
- [x] User: Person Icon
- [x] Active Icon colored

## Tasks
- [x] Create navbar
- [x] Create settings page
- [x] Change Icons
- [x] Update styleguide

## Complexity
(low, medium, high)
