### ISSUE TITLE
Avoid move call repetition

### ISSUE THREAD

**Issue by Hecktors** [Hecktors/rueda-de-casino#50]
## Value statement
As a **user** 
I need **to have on option to avoid consecutive repetition of a move call** 
so that **don't get consecutive repetition of the same move call** 

## Acceptance criteria
- [x] Adding checkbox on settings page
- [x] update move call behavior in session respectivly

## Tasks
- [x] Add checkbox
- [x] Update settings hook
- [x] Update appState
- [x] Implement logic into session hook 

## Complexity
medium
