### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by Hecktors** [Hecktors/rueda-de-casino#57]
## Value statement
As a **user** 
I need **to have the posibility to update my passport** 
so that **I'm able to renew it in case I forgot it** 

## Acceptance criteria
- [x] Create a 'forget password' link the login view
- [x] Create a send password view
- [x] Send a code to the email
- [x] Open a 'new password' form after entering code succsessfully

## Tasks
- [x] Inplement 'forget password' link to login view
- [x] Create send-code-form: 'email' input, 'send' button
- [x] user/require-code api: create temp token and save in user document
- [x] send email to user with token as link 
- [x] Create new-password-form: 'new password', 'confirm new password' input, 'send' button
- [x] Login and redirect to home view
- [x] Delete temp token 

## Complexity
high
