### ISSUE TITLE
Select moves form

### ISSUE THREAD

**Issue by Hecktors** [Hecktors/rueda-de-casino#8]
## Value statement
As a **user**
I need **I can select the moves to practice**
so that **I can pratice a set of moves on which I want to set the focus **

## Description
![image](https://user-images.githubusercontent.com/24996874/99916738-28a9b480-2d0c-11eb-9065-da877515c8c2.png)

## Acceptance criteria
- [x] In the start page is a button to open the settings
- [x] The settings includes all move divided by level
- [x] The settings includes a save button to store the selected moves
- [x] The settings includes a cacel button to leave the settings without saving
- [x] The settings includes a reset button to deselect al moves

## Tasks
- [x] data json: Wrap the move objects in level arrays
- [x] Create the form
- [x] Build the select, reset and cancel logic
- [x] Testing

## Size
large

**Comment by Hecktors** [comment]
## Value statement
As a **user**
I need **to hear the random move name after a specific amount of time**
so that **I know which move to dance**

## Description
![image](https://user-images.githubusercontent.com/24996874/99273751-bc214800-2829-11eb-9ce3-4f13a24d88b3.png)

## Acceptance criteria
- [x] The audio plays with the apperance of the current move name
- [x] The proximate move name is seen an heard after a break depending on its individual amount of steps

## Tasks
- [x] Add audio file for each move
- [x] Add path links to data.json
- [x] Build handle audio logic 

## Size
small
