### ISSUE TITLE
Song select

### ISSUE THREAD

**Issue by Hecktors** [Hecktors/rueda-de-casino#9]
## Value statement
As a **user** 
I need **I can select between 3 different songs** 
so that **I can choose between a slower, nomal speed, and faster song** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/24996874/99916885-25fb8f00-2d0d-11eb-8892-4ef27972d0f3.png)

## Acceptance criteria
- [ ] The settings form give the selection of 3 songs selectable by radio buttons

## Tasks
- [ ] Add 2 more songs
- [ ] With choosing and saving it is selected
- [ ] Test: Display 3 radio button with labels

## Size
small
